### ISSUE TITLE
Ajouter une license

### ISSUE THREAD

**Issue by imbjdd** [Semanteo/Genepix-bot#10]
## Contexte
Un code non-licensé est un code non-utilisable et que personne ne peut modifier. Il est impératif d'en ajouter une.

## Ressources
- https://dev.to/rduttshukla/importance-of-licensing-your-code-choosing-a-license-on-github-5hip
- https://choosealicense.com/
- https://choosealicense.com/no-permission/

**Comment by leolios** [comment]
@6346563751 On a proposé dans le package.json la CC 4.0 qui est pas mal est de plus en plus utilisé pour nos contextes.
Il y a le lien dedans justement, mais peut être la rendre plus visible dans le Readme et standardiser la façon de faire serait un plus

**Comment by imbjdd** [comment]
> @6346563751 On a proposé dans le package.json la CC 4.0 qui est pas mal est de plus en plus utilisé pour nos contextes.
> Il y a le lien dedans justement, mais peut être la rendre plus visible dans le Readme et standardiser la façon de faire serait un plus

Je ne l'avais pas vue. Au temps pour moi.
Pour la rendre plus visible, il y a aussi l'option de github d'ajouter un fichier LICENSE ou LICENSE.md qui permet de l'afficher en haut du repository.
Source : https://docs.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by leolios** [comment]
Oui, il propose quand tu créer le dépôt mais il ne propose pas la CC 4.0 dernière édition :-1:

**Comment by Semanteo** [comment]
Fait
