### ISSUE TITLE
[BUG] Mot réservé utilisé

### ISSUE THREAD

**Issue by leolios** [Semanteo/Genepix-bot#6]
@Semanteo 

:one:  Je viens de voir ton commit https://github.com/Semanteo/Genepix-bot/commit/d866cb14c31687dd11faebb6baeeca4ddc8237a1
    Il faut adapter tes données pour que ce soit avec le champ nomé par exemple bdd plutôt que database parce-que c'est un mot réservé en SQL pour des traitements des fois de core, je vais te montrer une ressource pour t'expliquer c'est très important de savoir ça dans le développement.

 La norme SQL spécifie un grand nombre de mots-clés qui ne peuvent pas être utilisés et database en fait partie, du coup, je comprends mieux pourquoi tu as eu un soucis c'est normal tu n'as pas mis à jour ton fichier de données etc..  :slight_smile:
Tu as une liste des mots réservé ici à ne jamais utiliser : https://www.sqlite.org/lang_keywords.html en principe ton IDE doit te le souligner il sert à ça sinon ajoute un plugin :wink:

:two: Tu as aussi la doc de Microsoft qui en parle puisqu'ils utilisent le SQL dans un des moteurs comme standard aussi comme SQLlite : https://support.microsoft.com/fr-fr/office/mots-r%C3%A9serv%C3%A9s-sql-b899948b-0e1c-4b56-9622-a03f8f07cfc8#bmdaidxsqld

La liste suivante répertorie tous les mots réservés par le moteur de base de données Microsoft Access pour une utilisation dans les instructions SQL. Les mots de la liste qui ne sont pas entièrement en majuscules sont également réservés par d’autres applications. Par conséquent, les rubriques d’aide individuelles de ces mots fournissent des descriptions générales qui ne s’appliquent pas uniquement à une utilisation dans les instructions SQL.

Référence : https://fr.qaz.wiki/wiki/Reserved_word

Dans un langage informatique , un mot réservé (également connu sous le nom d' identifiant réservé ) est un mot qui ne peut pas être utilisé comme identifiant , tel que le nom d'une variable, d'une fonction ou d'une étiquette - il est "réservé à l'usage". Il s'agit d'une définition syntaxique et un mot réservé peut n'avoir aucune signification.
 
Tu as aussi une liste pour le SQL standard : https://en.wikipedia.org/wiki/SQL_reserved_words
Mot | Système pour les données |
DATABASE     SQLite     DB2     —     MySQL     —     —     SQL Server     Teradata
DATABASES     —     —     —     MySQL     —     —     —     —

**Comment by Semanteo** [comment]
Merci de ce retour et oui le problème à été corrigé ^^
